version: 2

jobs:
  build:
    docker:
      - image: themattrix/tox

    steps:

      - run:
          name: Install DataSuper
          working_directory: /tmp
          command: |
            apt-get update; apt-get install -y git
            git clone https://github.com/dcdanko/DataSuper.git datasuper
            cd datasuper
            git checkout develop
            pip install -e .

      - checkout

      - run:
          name: Run tests with py27
          command: tox -e py27

      - run:
          name: Run tests with py34
          command: tox -e py34

      - run:
          name: Run tests with py35
          command: tox -e py35

      - run:
          name: Run tests with py36
          command: tox -e py36

      - run:
          name: Run tests with pypy
          command: tox -e pypy

      - run:
          name: Run tests with pypy3
          command: tox -e pypy3

      - run:
          name: Run tests with pylint
          command: tox -e pylint
