version: 2

jobs:
  build:
    docker:
      - image: themattrix/tox

    steps:
      - run:
          name: Install Git
          command: apt-get update; apt-get install -y git

      - checkout

      - run:
          name: Run tests with py35
          command: tox -e py35

      - run:
          name: Run tests with py36
          command: tox -e py36

      - run:
          name: Run tests with pypy3
          command: tox -e pypy3

      - run:
          name: Run pylint
          command: tox -e pylint
